org: willcarter
app: famous-http-api
service: famous-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getCountries:
    handler: handler.getCountries
    events:
      - http:
          method: get
          path: /getCountries
  getFamous:
    handler: handler.getFamous
    events:
      - http:
          method: get
          path: /getFamous
  getDomains:
    handler: handler.getDomains
    events:
      - http:
          method: get
          path: /getDomains
  getIndustries:
    handler: handler.getIndustries
    events:
      - http:
          method: get
          path: /getIndustries
  getOccupations:
    handler: handler.getOccupations
    events:
      - http:
          method: get
          path: /getOccupations

plugins:
  - serverless-offline