org: willcarter
app: famous-http-api
service: famous-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getCountries:
    handler: handler.getCountries
    events:
      - http:
          method: get
          path: /getCountries
  getFamous:
    handler: handler.getFamous
    events:
      - http:
          method: get
          path: /getFamous

plugins:
  - serverless-offline