import boto3
import private

session = boto3.Session(aws_access_key_id = private.aws_access_key_id, aws_secret_access_key = private.aws_secret_access_key)
s3 = session.resource('s3')

bad_images = []
bad_images.append('10010_vincent_candela.jpeg')
bad_images.append('10035_viswanathan_anand.jpeg')
bad_images.append('10163_whitney_houston.jpeg')
bad_images.append('10266_william_lawrence_bragg.jpeg')
bad_images.append('10499_zilda_arns.jpeg')
bad_images.append('1162_ben_gazzara.jpeg')
bad_images.append('1212_bernhard_riemann.jpeg')
bad_images.append('1245_bilawal_bhutto_zardari.png')
bad_images.append('1252_billie_holiday.jpg')
bad_images.append('1406_brigitte_nielsen.jpg')
bad_images.append('1422_bruno_kreisky.jpeg')
bad_images.append('1567_carmelo_anthony.jpg')
bad_images.append('1676_charles_durning.jpg')
bad_images.append('1685_charles_gounod.jpg')
bad_images.append('1849_christian_wulff.jpg')
bad_images.append('1878_christoph_schneider.jpeg')
bad_images.append('1942_clement_attlee.jpg')
bad_images.append('2006_constantine_vii.jpg')
bad_images.append('2011_coolio.jpg')
bad_images.append('2071_dalida.png')
bad_images.append('2092_daniel_bernoulli.jpg')
bad_images.append('2237_david_tennant.jpg')
bad_images.append('2280_denis_sassou_nguesso.jpg')
bad_images.append('2297_deron_williams.jpg')
bad_images.append('2417_donnie_yen.jpeg')
bad_images.append('2491_edgar_degas.jpeg')
bad_images.append('2609_einar_gerhardsen.jpeg')
bad_images.append('2665_elizabeth_of_york.jpg')
bad_images.append('2689_emanuel_lasker.jpg')
bad_images.append('2690_emanuel_swedenborg.png')
bad_images.append('2759_empress_elisabeth_of_austria.jpg')
bad_images.append('2854_ernst_kaltenbrunner.jpg')
bad_images.append('3191_frankie_muniz.jpg')
bad_images.append('3201_frank_rijkaard.jpg')
bad_images.append('4154_herbert_marcuse.jpeg')
bad_images.append('4174_hermann_oberth.jpg')
bad_images.append('4302_ian_fleming.jpg')
bad_images.append('4330_ice_cube.jpeg')
bad_images.append('4338_iggy_pop.jpeg')
bad_images.append('4389_inigo_jones.jpg')
bad_images.append('4524_jacob_grimm.jpg')
bad_images.append('4552_jacques_monod.jpg')
bad_images.append('4615_james_harden.jpg')
bad_images.append('4683_jane_seymour.jpg')
bad_images.append('5072_johannes_heesters.jpg')
bad_images.append('5129_john_carmack.jpeg')
bad_images.append('5483_j_p_morgan.jpeg')
bad_images.append('5720_kelly_rowland.jpg')
bad_images.append('5843_knut_hamsun.jpeg')
bad_images.append('6043_leonardo_dicaprio.jpeg')
bad_images.append('6332_luitzen_egbertus_jan_brouwer.jpeg')
bad_images.append('6333_luiz_felipe_scolari.jpeg')
bad_images.append('6567_marion_jones.jpeg')
bad_images.append('6619_martial.jpg')
bad_images.append('6794_max_jacob.jpg')
bad_images.append('6978_mickey_rourke.jpeg')
bad_images.append('7287_nestor_carbonell.jpeg')
bad_images.append('7449_norodom_sihanouk.jpg')
bad_images.append('7743_paul_ryan.jpg')
bad_images.append('7843_peter_ustinov.jpg')
bad_images.append('7940_pierre_de_marivaux.jpeg')
bad_images.append('8311_queen_of_sheba.jpg')
bad_images.append('8468_richard_arkwright.jpeg')
bad_images.append('8479_richard_dreyfuss.jpg')
bad_images.append('8691_robin_cook.jpg')
bad_images.append('8713_rodrigo_santoro.jpg')
bad_images.append('8755_romano_prodi.jpg')
bad_images.append('8890_saif_ali_khan.jpeg')
bad_images.append('9530_ted_hughes.jpeg')
bad_images.append('9605_theo_walcott.jpg')
bad_images.append('9955_veselin_topalov.jpg')

for b in bad_images:
    s3.meta.client.delete_object(Bucket='images-famous', Key=b)
    print("""file deleted: {}""".format(b))